let game={company:{name:"",day:1,money:1000000,sales:0,profit:0,customers:0,reputation:50,awareness:20},product:{name:"",cost:120,price:300,quality:50,popularity:50},market:{demand:100,economy:50,materialPrice:100,competitorPressure:50},personality:{challenge:0,caution:0,customer:0,profit:0,innovation:0,longTerm:0},history:[],news:[],today:{advertising:0,development:0,research:0}};

function startGame(){const companyName=document.getElementById("companyInput").value.trim();const productName=document.getElementById("productInput").value.trim();if(!companyName)return alert("会社名を入力してください。");if(!productName)return alert("商品名を入力してください。");game.company.name=companyName;game.product.name=productName;addHistory(`会社「${companyName}」を設立。商品「${productName}」の販売を開始。`);document.getElementById("startScreen").style.display="none";saveGame();updateUI();}

function updateUI(){document.getElementById("companyName").textContent=game.company.name;document.getElementById("day").textContent=`DAY ${game.company.day}`;document.getElementById("money").textContent=yen(game.company.money);document.getElementById("sales").textContent=yen(game.company.sales);document.getElementById("profit").textContent=yen(game.company.profit);document.getElementById("customers").textContent=game.company.customers.toLocaleString();document.getElementById("reputation").textContent=Math.round(game.company.reputation);document.getElementById("productName").textContent=game.product.name;document.getElementById("productCost").textContent=yen(game.product.cost);document.getElementById("productPrice").textContent=yen(game.product.price);document.getElementById("productQuality").textContent=Math.round(game.product.quality);updateNews();updateHistory();}

function advertising(){const cost=10000;if(!canPay(cost))return;game.company.money-=cost;game.company.awareness=Math.min(game.company.awareness+8,100);game.today.advertising+=cost;game.personality.challenge+=1;showResult("広告を実施しました。<br>認知度が上昇しました。");addHistory(`DAY ${game.company.day}：広告に${yen(cost)}投資。`);saveGame();updateUI();}

function developProduct(){const cost=20000;if(!canPay(cost))return;game.company.money-=cost;game.product.quality=Math.min(game.product.quality+random(2,5),100);game.product.popularity=Math.min(game.product.popularity+random(1,4),100);game.today.development+=cost;game.personality.innovation+=3;game.personality.longTerm+=1;showResult("商品開発を行いました。<br>品質と人気が上昇しました。");addHistory(`DAY ${game.company.day}：商品開発に${yen(cost)}投資。`);saveGame();updateUI();}

function marketResearch(){const cost=5000;if(!canPay(cost))return;game.company.money-=cost;game.today.research+=cost;game.personality.caution+=1;showResult(`市場調査を実施しました。<br>現在の市場需要：${Math.round(game.market.demand)}<br>景気指数：${Math.round(game.market.economy)}<br>競合圧力：${Math.round(game.market.competitorPressure)}`);addHistory(`DAY ${game.company.day}：市場調査を実施。`);saveGame();updateUI();}

function openPriceDialog(){const input=prompt(`現在の価格：${game.product.price}円\n\n新しい価格を入力してください。`,game.product.price);if(input===null)return;const price=Number(input);if(!Number.isFinite(price)||price<=0)return alert("正しい価格を入力してください。");game.product.price=Math.floor(price);game.personality.challenge+=1;addHistory(`DAY ${game.company.day}：商品価格を${yen(price)}に変更。`);showResult(`価格を${yen(price)}に変更しました。`);saveGame();updateUI();}

function restDay(){processDay();saveGame();updateUI();}

function processDay(){const p=game.product,m=game.market;let demand=m.demand;const priceRatio=p.price/p.cost;if(priceRatio<=1.5)demand*=1.25;else if(priceRatio<=2.5)demand*=1;else if(priceRatio<=4)demand*=.75;else demand*=.5;demand*=.7+p.quality/100;demand*=.7+p.popularity/100;demand*=.4+game.company.awareness/100;demand*=.6+game.company.reputation/100;demand*=.7+m.economy/100;demand*=1-m.competitorPressure/200;const customers=Math.max(0,Math.floor(demand/10+random(-10,15)));const sales=customers*p.price;const materialCost=customers*p.cost*(m.materialPrice/100);const fixedCost=3000;const advertisingCost=game.today.advertising;const profit=sales-materialCost-fixedCost-advertisingCost;game.company.money+=profit;game.company.sales=sales;game.company.profit=profit;game.company.customers=customers;if(p.quality>=70)game.company.reputation+=1;if(p.quality<40)game.company.reputation-=1;game.company.reputation=clamp(game.company.reputation,0,100);game.company.awareness=Math.max(0,game.company.awareness-1);updateMarket();generateNews();showResult(`<strong>DAY ${game.company.day} 経営結果</strong><br><br>顧客数：${customers.toLocaleString()}人<br>売上：${yen(sales)}<br>原材料費：${yen(materialCost)}<br>固定費：${yen(fixedCost)}<br>広告費：${yen(advertisingCost)}<br><br><strong>営業利益：${yen(profit)}</strong><br><br>現在の資金：${yen(game.company.money)}`);addHistory(`DAY ${game.company.day}：売上${yen(sales)} / 利益${yen(profit)} / 顧客${customers}人`);game.company.day++;game.today={advertising:0,development:0,research:0};if(game.company.money<0)showResult("<strong>資金不足</strong><br><br>現金がマイナスになりました。このままでは会社を維持できません。");}

function updateMarket(){game.market.demand=clamp(game.market.demand+random(-5,5),50,150);game.market.economy=clamp(game.market.economy+random(-3,3),20,100);game.market.materialPrice=clamp(game.market.materialPrice+random(-5,5),70,150);game.market.competitorPressure=clamp(game.market.competitorPressure+random(-3,3),10,90);}

function generateNews(){const n=[];if(game.market.economy>=80)n.push("景気が上向いています。消費者の購買意欲が高まっています。");if(game.market.economy<=30)n.push("景気が悪化しています。消費が落ち込む可能性があります。");if(game.market.materialPrice>=125)n.push("原材料価格が上昇しています。仕入れコストに注意してください。");if(game.market.demand>=120)n.push("市場需要が拡大しています。新規顧客を獲得する好機かもしれません。");if(game.market.competitorPressure>=75)n.push("競合企業の活動が活発化しています。価格や商品の動向に注意してください。");if(!n.length)n.push("市場に大きな変化はありません。");game.news.unshift({day:game.company.day,text:n[Math.floor(Math.random()*n.length)]});game.news=game.news.slice(0,10);}

function showResult(text){document.getElementById("result").innerHTML=text;}
function updateNews(){const e=document.getElementById("news");if(!game.news.length){e.textContent="会社を設立して経営を始めましょう。";return;}e.innerHTML=game.news.slice(0,3).map(n=>`<div><strong>DAY ${n.day}</strong>　${n.text}</div>`).join("<hr>");}
function updateHistory(){document.getElementById("history").innerHTML=game.history.slice().reverse().slice(0,30).map(item=>`<div class="history-item">${escapeHtml(item)}</div>`).join("");}
function addHistory(text){game.history.push(text);if(game.history.length>200)game.history=game.history.slice(-200);}
function saveGame(){localStorage.setItem("keieiSimulationSave",JSON.stringify(game));}
function loadGame(){const saved=localStorage.getItem("keieiSimulationSave");if(!saved)return;try{game=JSON.parse(saved);document.getElementById("startScreen").style.display="none";updateUI();}catch(e){console.error("セーブデータの読み込みに失敗しました。",e);}}
function canPay(amount){if(game.company.money<amount){alert(`資金が足りません。\n必要：${yen(amount)}`);return false;}return true;}
function yen(value){return "¥"+Math.floor(value).toLocaleString();}
function random(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function clamp(value,min,max){return Math.min(Math.max(value,min),max);}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
loadGame();
